//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab13
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3
    {
        public int Id { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<int> IdOrder { get; set; }
    
        public virtual T1 T1 { get; set; }
        public virtual T2 T2 { get; set; }
    }
}
