//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminToUser
    {
        public string AdminLogin { get; set; }
        public Nullable<int> UsersId { get; set; }
        public int UsersNumber { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
    }
}
