//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToTopic
    {
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TopicNumber { get; set; }
        public int Numbers { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
    }
}
