//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToTopic
    {
        public Nullable<int> UsersId { get; set; }
        public string Topic { get; set; }
        public int TopicNumbers { get; set; }
    
        public virtual Topic Topic1 { get; set; }
        public virtual User User { get; set; }
    }
}
